version: '3'

networks:
  cloud:
    driver: bridge

services:
  message-broker:
    image: rabbitmq:3.7-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=broker
      - RABBITMQ_DEFAULT_PASS=admin
    volumes:
      - ./data/message-broker:/var/lib/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - cloud
