### Authenticate

POST {{baseUrl}}/credentials
Accept: application/json
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Get messages

GET http://localhost:8181/api/v1/messages
#Authorization: Bearer {{token}}
Accept: application/json
Content-Type: application/json
###